// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTD7Efw_YknbLOF67W-CTD34ckPiIBcXU',
    appId: '1:566523664836:web:ddb66bb2fa8d9d89cfec91',
    messagingSenderId: '566523664836',
    projectId: 'todo-app-84654',
    authDomain: 'todo-app-84654.firebaseapp.com',
    storageBucket: 'todo-app-84654.appspot.com',
    measurementId: 'G-J6PQZTQ7Q8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDziKMx9Y8KGtzRNOcIUJsFwhh7uWqQmYY',
    appId: '1:566523664836:android:5d4521127100d2e6cfec91',
    messagingSenderId: '566523664836',
    projectId: 'todo-app-84654',
    storageBucket: 'todo-app-84654.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoWjuLDV9BY0-2bhK22UBqvTjvpP06WkQ',
    appId: '1:566523664836:ios:caceb775cd93b1eccfec91',
    messagingSenderId: '566523664836',
    projectId: 'todo-app-84654',
    storageBucket: 'todo-app-84654.appspot.com',
    iosBundleId: 'com.example.firebaseTodoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDoWjuLDV9BY0-2bhK22UBqvTjvpP06WkQ',
    appId: '1:566523664836:ios:caceb775cd93b1eccfec91',
    messagingSenderId: '566523664836',
    projectId: 'todo-app-84654',
    storageBucket: 'todo-app-84654.appspot.com',
    iosBundleId: 'com.example.firebaseTodoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCTD7Efw_YknbLOF67W-CTD34ckPiIBcXU',
    appId: '1:566523664836:web:b90e969513477ee3cfec91',
    messagingSenderId: '566523664836',
    projectId: 'todo-app-84654',
    authDomain: 'todo-app-84654.firebaseapp.com',
    storageBucket: 'todo-app-84654.appspot.com',
    measurementId: 'G-7L1W0FBX95',
  );
}
